In [1]:
import numpy as np

In [ ]:
episode = [(1, 2, 3), (4,5,6)]

states, actions, rewards = zip(*episode)

states, actions, rewards


((1, 4), (2, 5), (3, 6))

In [6]:
list(zip(states, actions, rewards))

[(1, 2, 3), (4, 5, 6)]

In [5]:
x = zip((1,2,3), (4,5,6))
list(x)

[(1, 4), (2, 5), (3, 6)]

In [14]:
a = [(np.random.randint(0, 5), np.random.randint(0, 5)) for _ in range(3)]
a

[(1, 4), (0, 1), (1, 2)]

In [15]:
eps = [(1,2,3), (4,5,6)]

for (s,a,r) in eps:
    print(s, a, r)

1 2 3
4 5 6


In [22]:
done = [False, True, False]
if True in done:
    print("yes")
else:
    print("no")

yes


In [23]:
for i in range(5):
    print(i)

print(i)

0
1
2
3
4
4


In [96]:
b = np.ones((3,3), dtype=bool)
b[[0,1,2],[0,1,2]] = False

valid_actions = np.where(b==True)   # arr of rows and arr of cols

valid_actions = list(zip(*valid_actions))  # turn into tuple pairs
valid_actions
#states[np.random.choice(len(states))]


[(0, 1), (0, 2), (1, 0), (1, 2), (2, 0), (2, 1)]

In [78]:
np.random.choice(3)

2

In [141]:
dict1 = {(0,0): 4, (0,2):1, (0,1):3}
key,val = max(dict1.items(), key=lambda pair: pair[1])
key,val

((0, 0), 4)

In [ ]:
# ineffiecient
q_vals = np.array([[6,2,3],
                  [4,5,6],
                  [7,1,9]])

action_space = np.array([[True, True, False],
                         [False, False, False],
                         [True, True, False]])

valid_actions = np.where(action_space==True)   # arr of rows and arr of cols

valid_actions = list(zip(*valid_actions))  # turn into tuple pairs

value_idx_dict = {q_vals[idx]:idx for idx in valid_actions}
print(value_idx_dict)

best_action_value, best_action_idx = max(value_idx_dict.items())
print(best_action_value, best_action_idx)

{6: (0, 0), 2: (0, 1), 7: (2, 0), 1: (2, 1)}
7 (2, 0)


In [165]:
# efficient
q_vals = np.array([[5,2,3],
                  [4,5,6],
                  [7,1,9]])

action_space = np.array([[True, True, False],
                         [False, False, False],
                         [True, True, False]])

# np.where(condition, val if true, val if false)
valid_actions = np.where(action_space, q_vals, -np.inf) # invalid actions masked
print(valid_actions)

# exploit
flat_idx = np.argmax(valid_actions)
print(flat_idx) 

best_idx = np.unravel_index(flat_idx, q_vals.shape)
print(best_idx)

# explore
flat_valid_idxs = np.flatnonzero(action_space)
print(flat_valid_idxs)

idx = np.random.choice(flat_valid_idxs)

random_idx = np.unravel_index(idx, q_vals.shape)
print(random_idx)


[[  5.   2. -inf]
 [-inf -inf -inf]
 [  7.   1. -inf]]
6
(2, 0)
[0 1 6 7]
(2, 0)


In [106]:
# unravels 1d idx to higher dims

i = 5   # 1d index
idx = np.unravel_index(i, shape=(3,3))
idx

(1, 2)

In [171]:
state = np.array([[0,0,1],
                  [2,0,0],
                  [0,0,0]])

powers = 3**np.arange(9)

state.flatten() @ powers

63

In [ ]:
arr = np.array([1,4,5,2,5,7,5])
np.max(arr)
#np.maximum(arr)

TypeError: maximum() takes from 2 to 3 positional arguments but 1 were given

In [176]:
s = np.array([2,4,6,3])
a = s*2
a

array([ 4,  8, 12,  6])

In [179]:
board = np.array([1,1,2,1,2,1])
sum(board==0)

0

In [201]:
q_vals = np.array([5,7,3,6,8,1,1,1,3])

board = np.array([2,1,0,0,1,2,1,0,0])

valid_actions = (board == 0)    # [True, True, False ...]

valid = np.flatnonzero(valid_actions)  # [2,3,7,8]    0 indices
#valid
idx = np.random.choice(valid)
idx

7

In [219]:
board = np.array([1,1,1,0,0,2,2,0,0])
board1 = (board==1)

line = (1,2,3)
board1[[*line]]

array([ True,  True, False])

In [237]:
win_lines = [np.array([0,1,2]), # top row
                          [3,4,5], # mid row
                          [6,7,8], # bot row
                          [0,3,6], # 1st col
                          [1,4,7], # 2nd col
                          [2,5,8], # 3rd col
                          [0,4,8], # main diag
                          [2,4,6]  # other diag
                          ]

board = np.array([1,1,1,0,0,0,2,2,2])
board1 = (board==1)

is_win = False
for line in win_lines:

    if board1[line].all():   # if all elements in arr are True, then True
        is_win = True
        break
print(is_win)


True


In [ ]:
x= np.array([1,3,5,2,3,4,5,3])
#x.size
y = np.zeros(x.shape) # size also works

for i in y:
    print(i)

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0


In [235]:
x = np.array([1,2,3,4,4,5])
x.reshape(2,3)

array([[1, 2, 3],
       [4, 4, 5]])

In [236]:
for i in range(3, 5):
    print(i)

3
4


In [ ]:
np.arange() # start stop step